apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-config
  namespace: apollo-system
  labels:
    app: apollo-api
data:
  APP_ENV: "production"
  FEATURE_FLAGS: |
    investigations:true
    surveillance:true
    blockchain:true
