apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: apollo-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-db
  namespace: apollo-system
spec:
  podSelector:
    matchLabels:
      app: apollo-postgresql
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              mesh: apollo
          podSelector:
            matchLabels:
              app: apollo-api
      ports:
        - port: 5432
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              mesh: apollo
      ports:
        - port: 5432
