version: '3.9'
services:
  api:
    image: ghcr.io/security-threat-intel/apollo:${APOLLO_VERSION:-latest}
    env_file: ../../..//.env
    deploy:
      replicas: 3
      update_config:
        order: start-first
      resources:
        limits:
          cpus: '1.5'
          memory: 1.5G
    depends_on:
      - postgres
      - redis
    networks:
      - edge
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: apollo
      POSTGRES_USER: apollo_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    networks:
      - edge
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - edge
networks:
  edge:
    driver: bridge
volumes:
  pgdata-prod:
