apiVersion: v1
kind: Service
metadata:
  name: apollo-postgresql
  namespace: apollo-system
spec:
  type: ClusterIP
  selector:
    app: apollo-postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-neo4j
  namespace: apollo-system
spec:
  selector:
    app: apollo-neo4j
  ports:
    - name: http
      port: 7474
    - name: bolt
      port: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-redis
  namespace: apollo-system
spec:
  selector:
    app: apollo-redis
  ports:
    - port: 6379
      targetPort: 6379
